### PR TITLE
Remove error in Android Studio about version of dependencies

### PR DESCRIPTION
**Pull request by HoDuyQuang**
Thanks for proposing a pull request.

To help us review the request, please complete the following:
- [ ] sign contributor license agreement: https://developers.facebook.com/opensource/cla
- [ ] submit against our `:dev` branch, not `master`.
- [x] describe the change (for example, what happens before the change, and after the change)

Those libraries need to update to version 25.3.0 : appcompat-v7, support, cardview-v7, customtabs
Current version is 25.0.0, which conflict another Android Support library
It's done if you guy have a plan for it 👍

### CODE REVIEW

**Comment by janbolat** [comment]
Please update the SDK since it conflicts with the new 'com.android.support:appcompat-v7:25.3.0' package. Thank you

**Comment by molind** [comment]
Last version 25.3.1 already and seems no one cares. :(

**Comment by sirolei** [comment]
please update to 25.3.1

**Comment by dzhuowen** [comment]
outdated. see #499

**Pull request closed without merging**
