### PR TITLE
Fix null pointer for tests

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Fixes https://github.com/robolectric/robolectric/issues/2579 and 
https://developers.facebook.com/bugs/595476800600441/.

Explanation as to why this fixes the issue: https://github.com/robolectric/robolectric/issues/2579#issuecomment-276526911.

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
I signed it!

**Comment by SUPERCILEX** [comment]
@dzhuowen @fransanchez PTAL

**Comment by dzhuowen** [comment]
Thanks for PR! We'll fix this issue in next release. Unfortunately we can't merge it here since it's from `unknown repository`

**Comment by SUPERCILEX** [comment]
@dzhuowen My bad, I deleted the repo thinking GitHub would still let you merge. Anyway, I've recreated this PR here: #500.

**Pull request closed without merging**
