### PR TITLE
Fix request parsing to handle any passed-in request parameters

### PR DESCRIPTION
**Pull request by mikelambert**
On iOS, this works:
GraphRequest("/me?fields=id")

On Android, it does not, and the resulting URL looks like:
"/me?fields=id?access_token=X&other=params&included=here" (notice the two "?" chars)

This causes a very strange problem when react-native-fbsdk assumes they perform identically, as seen here:
facebook/react-native-fbsdk#105

This should fix the issue and bring feature parity between iOS and Android.

### CODE REVIEW

**Comment by mingflifb** [comment]
This actually breaks if you create a batch request where there are dependencies between requests (https://developers.facebook.com/docs/graph-api/making-multiple-requests#operations).

This is because the relative path (or baseUrl) can look something like: 

v2.7/{result=create:$.id}

In which case Uri.parse doesn't actually parse it correctly as a path (it will see the ':' and think that v2.7/{result=create is the scheme part of the uri instead). The GraphRequestTest gives a good example of where this can fail (https://github.com/facebook/facebook-android-sdk/blob/master/facebook/src/androidTest/java/com/facebook/GraphRequestTests.java).

**Comment by mikelambert** [comment]
Sounds like a bug in `Uri.parse`, which is unfortunate.

I've fixed `getUrlForBatchedRequest` to generates full URLs with schemes, and match what is done in `getUrlForSingleRequest`. My run of `gradlew test` appears to pass okay...curious how the Travis CI performs (and curious why `GraphRequestTest` didn't fail when I pushed this change up last time?)

**Comment by mingflifb** [comment]
Unfortunately, this doesn't really work either because our batch requests expect relative urls later on.

The reason that travis didn't catch this is because travis only runs our unit tests, and not our integration tests (because that requires the app secret to be stored somewhere). There are actually two GraphRequestTest classes, one in facebook/src/test, and another in facebook/src/androidTest. The one in facebook/src/androidTest is the integration test. If you have a facebook app, you can run the scripts/configure_unit_tests.sh script to set up your environment and try to run the integration test. It currently fails for me.

**Comment by mikelambert** [comment]
Okay, I have run `scripts/configure_unit_tests.sh`, but `./gradlew test` still completes successfully, so I suspect I'm not actually running the integration tests yet. What's the command to run them?

**Comment by mingflifb** [comment]
I load up the project in Android Studio and run All Tests under androidTest/java

**Comment by mikelambert** [comment]
I've pushed up a fix to use relative URLs for batched requests, but still untested on the integration tests.

The test users that are created in my app (with valid access tokens!) are unable to access TourEiffel or SpaceNeedle graph objects, preventing me from running the tests. This applies even to the SingleGet (ie non-batched) request tests.

When I copy the SingleGet requests to my browser, they fail with error 100, "Unsupported get request. Object with ID 'TourEiffel' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api", and prevent the tests from passing.

When I replace the access token of the test user for my app) with my own access token, the request completes fine. So I'm not sure what's wrong with the test users' access tokens when running the integration test myself...

If you had time to run the integration tests again yourself, they might just work now. (I tried to verify the returned relative URLs as best I could, even if I couldn't complete the tests!)

**Comment by mingflifb** [comment]
Thanks for your contribution.

**Pull request merged**
