### PR TITLE
Updated README.mdown

### PR DESCRIPTION
**Pull request by Grandolf49**
Thanks for proposing a pull request!

To help us review the request, please complete the following:

- [x] sign [contributor license agreement](https://developers.facebook.com/opensource/cla)
- [x] I've ensured that all existing tests pass and added tests (when/where necessary)
- [x] I've updated the documentation (when/where necessary) and [Changelog](CHANGELOG.md) (when/where necessary)
- [x] I've added the proper label to this pull request (e.g. `bug` for bug fixes)

## Pull Request Details

Fixed the incorrect URL for Contributing Guidelines in readme.md file.

## Test Plan

NA

### CODE REVIEW

**Comment by Grandolf49** [comment]
Hi @KylinChang ! Can you please review this PR

**Comment by Grandolf49** [comment]
Hi! Can you please help me find where the build is failing? Earlier the build was passing and I haven't made changes to the source code.

**Comment by Nathaaaalie** [comment]
Hi @Grandolf49, the Builds & Tests has already passed after rebasing on the recent master branch.

**Comment by Grandolf49** [comment]
Hi @Nathaaaalie Thanks for notifying.

**Pull request closed without merging**
