### PR TITLE
Fix recreating FacebookActivity with LoginFragment

### PR DESCRIPTION
**Pull request by admund**
Thanks for proposing a pull request!

To help us review the request, please complete the following:

- [x] sign [contributor license agreement](https://developers.facebook.com/opensource/cla)
- [x] I've ensured that all existing tests pass and added tests (when/where necessary)
- [x] I've updated the documentation (when/where necessary) and [Changelog](CHANGELOG.md) (when/where necessary)
- [x] I've added the proper label to this pull request (e.g. `bug` for bug fixes)

## Pull Request Details

Fix for this issue https://github.com/facebook/facebook-android-sdk/issues/1151
When we try to recreate FacebookActivity with LoginFragment, we need to reinitialize SDK first, then we can start recreating fragments.

## Test Plan

Test Plan: **Add your test plan here**

### CODE REVIEW

**Review by Kryslynn93 — COMMENTED** [review]
approved

**Review by Kryslynn93 — COMMENTED** [review]
approved

**Review by Kryslynn93 — COMMENTED** [review]
ok

**Comment by sleepym09** [comment]
Hello, facebook team, Is there any update about this PR, I still face the same issue.

**Pull request closed without merging**
