### PR TITLE
Update build tools to 25.0.2

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates the build tools to the latest version `25.0.2`.

### CODE REVIEW

**Comment by sschuberth** [comment]
You also need to add that build-tools version to [.travis.yml](https://github.com/facebook/facebook-android-sdk/blob/dev/.travis.yml).

**Comment by friederbluemle** [comment]
@sschuberth I did update .travis.yml as well.. Not sure why Travis errored. Anyway, I rebased and amended my commit to reflect the now latest version `25.0.1`.

**Comment by sschuberth** [comment]
@friederbluemle FYI, I was experimenting with upgrading to Android Gradle plugin 2.2 to be able to use the SDK auto-download feature, getting rid of the need to maintain installed SDK component on Travis CI. I've also included upgrading the build-tools to version 25.0.1. Please have a look: https://github.com/facebook/facebook-android-sdk/pull/490

**Comment by dzhuowen** [comment]
See #499

**Comment by sschuberth** [comment]
@dzhuowen How is #499, which updates the support libraries, related to this PR, which updates the build tools?

**Comment by friederbluemle** [comment]
It's not related at all. Ideally this PR should have been merged first, after which @sschuberth would have rebased #490 with the very useful changes over there. Sadly, the way Facebook manages branches and handles pull requests of this open source repo here on GitHub leaves a lot of room for improvements...

**Pull request closed without merging**
