### PR TITLE
setCurrentAccessToken changed.

### PR DESCRIPTION
**Pull request by sangpan**
check argument token expiration.

I think it's better to checking argument token before set.
It will be resolve some token expired situation maybe.

I updated similar logic on iOS repository.

Thanks for proposing a pull request.

To help us review the request, please complete the following:
- [x] sign contributor license agreement: https://developers.facebook.com/opensource/cla
- [x] submit against our `:dev` branch, not `master`.
- [x] describe the change (for example, what happens before the change, and after the change)

### CODE REVIEW

**Comment by khp** [comment]
Hi sangpan, do you have examples of any particular issue that this resolves? Thanks!

**Comment by sangpan** [comment]
iOS facebook SDK has _FBSDKLoginRecoveryAttempter class. it help reconnect or reauthorize facebook account when accessToken is expired. but Android is not.

**for example calling graph API /me**
```
			parameter.putString("fields", "id,email,name,picture{url}");
			final GraphRequest request = new GraphRequest(currentAccessToken, "/me", parameter, HttpMethod.GET, new GraphRequest.Callback() {
				
				@Override
				public void onCompleted(GraphResponse response) {
...

```

1. Login with facebook SDK
2. token expired. (with temporl test account that created on developers.facebook.com)
3. request /me 
4. exit and re-run App.
5. request /me 

* before apply this commit 4.33.0, 4.35.0

we can find below log with 3/5 phase.

GraphResponse: {HttpStatus: 400, errorCode: 190, subErrorCode: 493, errorType: OAuthException, errorMessage: The access token is invalid since the user hasn't engaged the app in longer than 90 days.}

Surely, there is another way against expired token by handling above error.

* after apply this commit 4.33.0

SDK retry connect expired account with 5 phase.

**Comment by ravirajjak** [comment]
How can we identify if token is Expired?

**Comment by khp** [comment]
@ravirajjak You can check with `AccessToken.isCurrentAccessTokenActive()`

Hi @sangpan, thanks for your feedback.

**Pull request merged**
