### PR TITLE
Use LoginButton with native android.app.Fragment

### PR DESCRIPTION
**Pull request by Archinamon**
If we use API 15+ in our application, then no need to build fragment basing on android.support.v4.Fragment class. There was no way to use native android.app.Fragment class.

### CODE REVIEW

**Comment by bryant1410** [comment]
I think this should be reconsidered, as the new API minimum is now 15

**Comment by bryant1410** [comment]
@swiese: what do you think?

**Comment by bryant1410** [comment]
Is there a possibility to support both support fragments and native ones?

**Comment by swiese** [comment]
Its definitely possible to now support both fragments now. Although we currently don't have plans do the engineering work to support this feature at this time.

**Comment by PopsBGone69** [comment]
1-866-333-4606

**Comment by swiese** [comment]
We now support this behavior

**Comment by bryant1410** [comment]
Yeah I noticed! :smile:

**Comment by PopsBGone69** [comment]
Harleysandmusic65@yahoo.com

Sent from my MetroPCS 4G LTE Android device

**Comment by PopsBGone69** [comment]
Pops B Gone profile.Pops

**Comment by bryant1410** [comment]
This spam is annoying

**Pull request closed without merging**
