### PR TITLE
add activity result handling via result registry

### LINKED ISSUE #875: Use ActivityResultContracts as onActivityResult is deprecated
```
/**
     * Receive the result from a previous call to
     * {@link #startActivityForResult(Intent, int)}.  This follows the
     * related Activity API as described there in
     * {@link Activity#onActivityResult(int, int, Intent)}.
     *
     * @param requestCode The integer request code originally supplied to
     *                    startActivityForResult(), allowing you to identify who this
     *                    result came from.
     * @param resultCode The integer result code returned by the child activity
     *                   through its setResult().
     * @param data An Intent, which can return result data to the caller
     *               (various data can be attached to Intent "extras").
     *
     * @deprecated use
     * {@link #registerForActivityResult(ActivityResultContract, ActivityResultCallback)}
     * with the appropriate {@link ActivityResultContract} and handling the result in the
     * {@link ActivityResultCallback#onActivityResult(Object) callback}.
     */
    @SuppressWarnings("DeprecatedIsStillUsed")
    @Deprecated
    public void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        if (FragmentManager.isLoggingEnabled(Log.VERBOSE)) {
            Log.v(FragmentManager.TAG, "Fragment " + this + " received the following in "
                    + "onActivityResult(): requestCode: " + requestCode + " resultCode: "
                    + resultCode + " data: " + data);
        }
    }
```

### PR DESCRIPTION
**Pull request by bishiboosh**
Thanks for proposing a pull request!

To help us review the request, please complete the following:

- [x] sign [contributor license agreement](https://developers.facebook.com/opensource/cla)
- [x] I've ensured that all existing tests pass and added tests (when/where necessary)
- [x] I've updated the documentation (when/where necessary) and [Changelog](CHANGELOG.md) (when/where necessary)

## Pull Request Details

This fixes #875 by adding an alternative using `ActivityResultLauncher` for the methods in `LoginManager`

### CODE REVIEW

**Comment by bulutaysarac** [comment]
When will this be available to use officially? I hate using deprecated methos. :(

**Comment by Berki2021** [comment]
When will this be pushed? We need a new way to login due to deprecation. Please facebook, do something...

**Comment by tenjua** [comment]
Archivos modificados

**Comment by Hussienfahmy** [comment]
any updates ?

**Comment by dnkilic** [comment]
I wish I can delete whole facebook login from our app

**Comment by linmx0130** [comment]
Hi @bishiboosh! I really appreciate your pull request for fixing it! It does help us in our final implementation in supporting Androidx activity result APIs. In the v12.0, the new implementation will have following features:
1. Both `LoginButton` and `ShareButton` support Androidx activity result APIs.
2. The developers won't need to declare that the button is using result registry. It will be applied automatically if the context is from `androidx.activity` v1.2.0+.

Thank you again for your patience and your contribution to our SDK! We wish that you will love the new v12.0, which will be released in early October!

**Pull request closed without merging**
