### PR TITLE
CONTRIBUTING.mdown

### PR DESCRIPTION
**Pull request by Mohd4633**
Thanks for proposing a pull request!

To help us review the request, please complete the following:

- [x] sign [contributor license agreement](https://developers.facebook.com/opensource/cla)
- [x] I've ensured that all existing tests pass and added tests (when/where necessary)
- [x] I've updated the documentation (when/where necessary) and [Changelog](CHANGELOG.md) (when/where necessary)
- [x] I've added the proper label to this pull request (e.g. `bug` for bug fixes)

## Pull Request Details

Describe what you accomplished in this pull request (for example, what happens before the change, and after the change)

## Test Plan

Test Plan: **Add your test plan here**

### CODE REVIEW

**Comment by Mohd4633** [comment]
#660

**Comment by Mohd4633** [comment]
(#660 ) Facebook open source project.

**Comment by Mohd4633** [comment]
#660Facebook open source project.

**Comment by Mohd4633** [comment]
#660   Facebook open source project.

**Review by alshamiri5 — APPROVED** [review]

**Comment by friederbluemle** [comment]
Any reason why the file was renamed from `CONTRIBUTING.mdown` to `CONTRIBUTING.mdowna`?

If anything, it should probably renamed to the default `CONTRIBUTING.md`..

cc @rightparen for additional info on the `mdown` extension (b0429e5984e68e371610e007633a119b75b45ff4)

**Comment by rightparen** [comment]
@friederbluemle sorry I don't remember what motivated the change to `.mdown` here at the time, but agreed that `.md` would be better at this point.  Also, perhaps GitHub is not showing me a correct view of this PR, but the change contents also look incorrect.

**Comment by jawwad** [comment]
Closing this PR since the proposed changes (https://github.com/facebook/facebook-android-sdk/pull/660/files) don't look correct.

**Pull request closed without merging**
