### PR TITLE
Native with web view fallback login behaviour

### PR DESCRIPTION
**Pull request by jvanderwee**
Added behaviour which attempts login in using the Facebook App, and if that does not work falls back to web view dialog auth.

### CODE REVIEW

**Comment by friederbluemle** [comment]
@jvanderwee You should rebase your one commit onto the latest `dev` branch to remove all the unrelated commits from this PR.

**Comment by jvanderwee** [comment]
@friederbluemle thanks, I have now rebased

**Comment by mingflifb** [comment]
What's your use case for this behavior? The default behavior already falls back to chrome custom tabs or webview (if CCT is not available). Why are you trying to force webview?

**Comment by jvanderwee** [comment]
I have multiple apps using the same Facebook ID, when falling back to chrome custom tabs the user is prompted which app they wish to open, presumably because both apps have the same login protocol scheme.

**Comment by egk35** [comment]
@jvanderwee I don't think this is a behavior we should be supporting. Ideally, your apps would use different Facebook IDs but you could just remove the Chrome Custom Tab manifest elements from any additional apps that would use the same protocol scheme.

**Pull request closed without merging**
