### PR TITLE
4.x branch

### PR DESCRIPTION
**Pull request by samat83**
### **Thanks** for proposing a pull request!

To help us review the request, please complete the following:

- [ ] sign [contributor license agreement](https://developers.facebook.com/opensource/cla)
- [ ] I've ensured that all existing tests pass and added tests (when/where necessary)
- [ ] I've updated the documentation (when/where necessary) and [Changelog](CHANGELOG.md) (when/where necessary)
- [ ] I've added the proper label to this pull request (e.g. `bug` for bug fixes)

## Pull Request Details

Describe what you accomplished in this pull request (for example, what happens before the change, and after the change)

## Test Plan

Test Plan: **Add your test plan here**

### CODE REVIEW

**Comment by joe198** [comment]
upgraded

**Review by liwenyong887 — APPROVED** [review]

**Review by joe198 — COMMENTED** [review]
i request latest Sd face book,

**Comment by xilosada** [comment]
Hi, it seems like this pull request has been open for a long time but the CLA wasn't signed. We have made many changes in the SDK since then. If these changes are still relevant, please sign the CLA and open a new pull request.

**Comment by Motoneige-Sled** [comment]
TEST

**Comment by fernando010288** [comment]
Hola

**Pull request closed without merging**
